WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS 'GENERATION'
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.GENERATION + 1
    FROM ECOLI_DATA E 
    JOIN CTE C ON C.ID = E.PARENT_ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE C
LEFT JOIN ECOLI_DATA E ON C.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY 2
ORDER BY 2