SELECT
    O.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_ORDER O 
    INNER JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY 3 DESC, 1