SELECT
    R.HISTORY_ID,
    FLOOR(C.DAILY_FEE * (DATEDIFF(R.END_DATE, R.START_DATE) + 1) * (100 - COALESCE(DP.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    JOIN CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON DP.CAR_TYPE = '트럭' 
        AND DP.DURATION_TYPE = CASE
            WHEN (DATEDIFF(R.END_DATE, R.START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(R.END_DATE, R.START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(R.END_DATE, R.START_DATE) + 1) >= 7  THEN '7일 이상'
        ELSE NULL
        END
ORDER BY FEE DESC, R.HISTORY_ID DESC