SELECT
    A.FLAVOR
FROM (SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
      FROM FIRST_HALF
      UNION 
      SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
      FROM JULY) AS A
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) DESC
LIMIT 3