SELECT e.ID, e.GENOTYPE, p.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA e 
JOIN ECOLI_DATA p ON e.PARENT_ID = p.ID
WHERE p.GENOTYPE IS NOT NULL
    AND p.GENOTYPE = (e.GENOTYPE & p.GENOTYPE)
ORDER BY e.ID