SELECT
    e.ID,
    e.GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA e
    LEFT JOIN ECOLI_DATA p ON e.PARENT_ID = p.ID
    WHERE p.GENOTYPE = (e.GENOTYPE & p.GENOTYPE) AND p.GENOTYPE IS NOT NULL
ORDER BY e.ID