SELECT 
    A.BOARD_ID,
    A.WRITER_ID,
    A.TITLE,
    A.PRICE,
    CASE 
        WHEN A.STATUS = 'DONE' THEN '거래완료'
        WHEN A.STATUS = 'SALE' THEN '판매중'
        ELSE '예약중'
    END AS 'STATUS'
FROM USED_GOODS_BOARD A
WHERE A.CREATED_DATE = '2022-10-05'
ORDER BY A.BOARD_ID DESC